services:
  - type: web
    name: yukkoblog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application